FHIR/FSHOnline

- src/App.js
- src/components/CodeMirrorComponent.js
Fixes a bug where the cursor would jump to the end of the editor text if you tried to edit in the middle of a block of text.
This fixes this bug by only using the `value` prop to specify a default value. Previously, each time the component re-rendered, it put the current `prop.value` text into the editor and moved the cursor back to the beginning. I believe this current approach is the one that works better for the "uncontrolled" component that we are using.
> Fix cursor bug

- src/components/CodeMirrorComponent.js
This uses CodeMirror's [simple mode](https://codemirror.net/demo/simplemode.html) for defining a new language syntax highlighting. This mode uses regular expressions, similar to how our current VS Code extension works. Because of that, most of the regular expressions match the regular expressions in the VS Code extension. The tokens are used to categorize each regular expression and give them a specific color. I tried to match the colors based on the default color theme in VS Code. Pictures of a comparison are below.
The one difference between the regular expressions here and in the VS Code extension is the lack of look ahead and look behind. The simple mode approach for defining a language in Code Mirror can't support these. The purpose of the look behind/ahead is so that keywords that …
> FSH Syntax Highlighting

- src/components/RunButton.js
- src/components/TopBar.js
- src/tests/utils/Load.test.js
- src/utils/Load.js
This PR makes the call to fetch FHIR packages over https. To test this locally, I ran `HTTPS=true npm start`. When loading the packages (when you click the "Run" button), master will give you a `Mixed Content` error and this branch should properly load the packages. For more info on running it locally using HTTPS and for the script for windows, I used [this documentation](https://create-react-app.dev/docs/using-https-in-development/).
I also added the FSHSchool link to the documentation button since it didn't go anywhere previously.
> Support loading packages over https

- src/App.js
- src/components/ConsoleComponent.js
- src/components/JSONOutput.js
- src/components/RunButton.js
- src/components/TopBar.js
- src/index.css
- src/tests/components/ConsoleComponent.test.js
- src/tests/components/JSONOutput.test.js
- src/tests/components/RunButton.test.js
- src/utils/RunSUSHI.js
This PR includes small changes requested to FSH Online to get it to alpha capabilities. These changes include:
- Including the list of errors at the top of the right hand side pane. Just the error messages are displayed but the full output can still be found in the console at the bottom of the page.
- Removing the snapshot from the StructureDefinitions in the package we get back from SUSHI
- Opening all fields in the JSON output by default. Now that the snapshot is not on the profiles and extensions, opening all the fields by default seems much more manageable and seems to be preferable.
Update: e66703c also updates the fonts used on the site. I just tried to align the style a bit more with FSH School, but the fonts are still slightly off, but I thought they were at least closer. If …
> SUSHI Output updates

- config-overrides.js
- package-lock.json
- package.json
- src/tests/utils/Load.test.js
- src/tests/utils/Processing.test.js
- src/tests/utils/RunSUSHI.test.js
- src/utils/Processing.js
- src/utils/RunSUSHI.js
This PR updates FSH Online to use the latest version of SUSHI. It also updates the import statements to use the same method as GoFSH and includes the latest puns from SUSHI.
> Update SUSHI version

- src/App.js
- src/components/RunButton.js
- src/components/SUSHIControls.js
- src/tests/components/RunButton.test.js
- src/tests/components/SUSHIControls.test.js
- src/tests/utils/RunSUSHI.test.js
- src/utils/RunSUSHI.js
This PR supports basic user controls for SUSHI configuration. I believe the only SUSHI config options that should be applicable to the playground are `canonical`, `version`, and `dependencies`. This PR allows a user to specify the `canonical` and `version` and the field will be used by SUSHI when the "Run" button is clicked. Since we don't yet support loading any other dependencies besides R4, I added a disabled field for those, although it can be removed or commented out if that is easier. Also, if there is any feedback on the format/location of these controls, they can always be changed. The dialog box was my initial idea and it looked alright, but I'm no designer.
There is a warning in the console that gets logged by the Material UI Dialog component. I believe it is just a warning due …
> User Provided Configuration

- package-lock.json
- package.json
This upgrades SUSHI to 1.0.1. It also upgrades another few packages that `npm audit` said were out of date.
> Upgrade SUSHI (and other dependencies)

- src/components/SUSHIControls.js
- src/tests/components/SUSHIControls.test.js
- src/tests/utils/Load.test.js
- src/tests/utils/Processing.test.js
- src/utils/Load.js
- src/utils/Processing.js
- src/utils/RunSUSHI.js
Address issue #23, supporting non r4 dependencies. Users now have the ability to input different dependency packages. Each is stored in their own indexeddb object store, and should only be downloaded once. However with any given program run, FSHOnline will only add those packages listed in the user input to the sushi-used FHIR Defs. 
Also added the used dependencies to the console log, and an error if the dependency cannot be found to the console log.
> Enable dependencies

- src/tests/utils/Load.test.js
- src/tests/utils/Processing.test.js
- src/tests/utils/RunSUSHI.test.js
- src/utils/Load.js
- src/utils/Processing.js
- src/utils/RunSUSHI.js
Deletes empty ObjectStores that users have created in the past, the old 'resources' object store, and deletes any empty ObjectStores that users may create by entering unrecognized dependencies. Addresses comments made here: https://github.com/FSHSchool/FSHOnline/pull/28#issuecomment-754134629.
Note: there is still one test in `Load.test.js` that must be fixed or determined unnecessary.
> Object Store Clean Up

- package-lock.json
- package.json
- src/components/TopBar.js
- src/utils/RunSUSHI.js
This PR:
- updates the version of SUSHI to v1.1.0
- uses SUSHI's newly available `getRandomPun` function to use a random pun
- updates the hardcoded SUSHI version visible in the app. There's a separate task to investigate doing this in a different way.
> Update to SUSHI v1.1.0

- package-lock.json
- package.json
- src/components/SUSHIControls.js
- src/components/TopBar.js
This PR updates the installed SUSHI to the latest version, v1.2.0. This SUSHI update has a fix for using regex lookbehind assertions, and it fixes #34 so the app will load in Safari.
> Update to SUSHI v1.2.0

- package-lock.json
- package.json
- src/components/CodeMirrorComponent.js
- src/components/TopBar.js
Updates SUSHI to v1.3.0. This update should resolve the issue reported on SUSHI about an unexpected error message ([here](https://github.com/FHIR/sushi/issues/750)).
> Update SUSHI to v1.3.0

- package-lock.json
- package.json
- src/App.js
- src/components/ConsoleComponent.js
- src/components/JSONOutput.js
- src/components/SUSHIControls.js
- src/components/TopBar.js
- src/tests/components/ConsoleComponent.test.js
This PR address [CIMPL-683](https://standardhealthrecord.atlassian.net/browse/CIMPL-683), making the console expandable with an "Expand Console" button and also adding labels indicating how many warnings/errors resulted from the last run. I wanted the console to not make the actual editor page as a whole require any scrolling, so I've played around with some of the height values on the other components to get the height just right and not extend the content on the page to over 100% of the view screen.
> Collapsible console

- package-lock.json
- package.json
- src/App.js
- src/components/CodeMirrorComponent.js
- src/components/JSONOutput.js
- src/components/SUSHIControls.js
- src/style/CodeMirrorComponent.css
- src/tests/components/JSONOutput.test.js
- src/tests/components/SUSHIControls.test.js
This PR replaces the current RHS of FSH Online with an editor that can be used to for GoFSH inputs.
Currently, when you type in FSH on the LHS and run SUSHI, the editor on the RHS will populate with the first definition in the package. There is a very simple file navigator on the right that will let you switch to any other definitions that were in the package. Clicking a different definition should update the text in the editor, but the majority of the styling and organization for the file list will be part of a different PR (because it is a separate task). Additionally, you can edit the text in the RHS editor and then run GoFSH. The LHS FSH editor should populate with the resulting FSH.
This PR also updates the editor to use a placeholder plugin to display the initial text in the …
> Initial GoFSH editor

- package-lock.json
- package.json
- src/App.js
- src/components/JSONOutput.js
- src/components/SUSHIControls.js
- src/tests/components/JSONOutput.test.js
- src/tests/components/SUSHIControls.test.js
This PR updates the file tree that is rendered on the RHS editor.
A few features of the file tree:
- If the JSON entered for that definition is valid, a check mark is displayed next to its name
- If the JSON is invalid, an X is displayed next to it and the text is colored red and bolded (I don't actually think the bolding is necessary since there is a non-color based visual with the X and I didn't mind it, so I left it for others' opinions)
- Choosing a different definition switches the definition loaded in the editor
- Changing the `id` property in the JSON updates the text in the file tree
- Changing the `resourceType` will re-sort the definition. If it is anything besides "StructureDefinition", "ValueSet", or "CodeSystem", it is sorted under "Instances".
A few implementation/code …
> Updated JSON Definition File Tree

- src/components/CodeMirrorComponent.js
- src/style/CodeMirrorComponent.css
This PR adds two plugins to both editors:
- Auto close brackets will automatically close `()`, `[]`, `{},` `''`, `""`
- Code folding will let you collapse different brackets in the JSON editor. There is an arrow in the gutter that lets you collapse/expand sections similar to VS Code. Also, the example in the documentation also added the collapse/expand to the `Ctrl-Q` keyboard shortcut, so I included that as well. When a section is collapsed, it can also be expanded by clicking the arrow that appears between the collapsed brackets.
Since this just adds existing code mirror plugins, I couldn't think of any tests to add.
> Code Fold and Auto Close Bracket plugins

- src/components/JSONOutput.js
- src/components/SUSHIControls.js
- src/tests/components/JSONOutput.test.js
- src/tests/components/SUSHIControls.test.js
This PR adds a "Add definition" button to the file tree on the RHS. This lets you add a blank definition and open a blank editor to type the definition into. As you add text to the definition, the definition should be sorted into the correct category in the file tree and the id should populate.
This also adds a delete button so you can remove a full definition. Deleting the definition will remove it from the file tree and will remove it from the set of definitions that GoFSH is run on if you use the "Run GoFSH" button.
> Add Definition and Delete Definition buttons

- src/components/FSHControls.js
- src/tests/components/FSHControls.test.js
- src/tests/utils/FSHHelpers.test.js
- src/utils/FSHHelpers.js
This PR updates how the Configuration modals works with GoFSH and SUSHI so that we can successfully "round trip" within FSH Online.
When no values are set, we leave the fields blank and indicate the default values that SUSHI will use. If there are no values set when SUSHI runs, it will use the default `example.org` and `1.0.0` values. If there are no values when GoFSH is run, GoFSH will infer the values from the definitions, and then set the canonical and version value in modal, which will be used by SUSHI the next time SUSHI is run, completing the round trip.
If there are values set in modal when running SUSHI, SUSHI will use those. If there are values set in the modal when running GoFSH, GoFSH will use those as the configuration and set caret value rules for the actual canonical and …
> Canonical and Version configuration updates

- public/index.html
- src/App.js
- src/components/CodeMirrorComponent.js
- src/components/ConsoleComponent.js
- src/components/FSHControls.js
- src/components/FSHOutput.js
- src/components/JSONOutput.js
- src/components/ShareLink.js
- src/components/TopBar.js
- src/index.css
- src/style/CodeMirrorComponent.css
- src/style/TopBarStyling.css
- src/tests/components/JSONOutput.test.js
This PR contains a few design updates based on feedback from Mark and Noranda, including:
- Making it clearer that there are several editor essentially one behind the other and tying the definition list more closely with the RHS JSON editor by updating the "active definition" color to match the color of the editor. (Note that this style is similar to OneNote, which Mark mentioned [here](https://mitrecorp.slack.com/archives/CSQV7N91A/p1619635053019800))
- Updating the scrollbar style. The main motivation for this is for Windows users. The Mac scrollbars disappear by default when you're not scrolling, but Windows's don't ,and they were the default white color, which also contributed to the disconnect between the editor and the definition list. This updates the style for both Mac and Windows …
> Design updates based on feedback

- package-lock.json
- src/components/CodeMirrorComponent.js
This PR updates the FSH syntax highlighting to more closely match what is in the VS Code extension. This adds a few new updates to the highlighting:
- Includes the `+` as a symbol (this is actually not supported in the VS Code extension, but I'll include it there as well)
- New keywords for Logical and Resource
- Highlights numbers
- Highlights quoted codes (`#"code with spaces"`)
- Highlight single quoted ucum units (`'lb'`)
- Highlight Reference and Canonical keyword. In the VS Code extension, we used more than just a regular expression to match the start and end parentheses without highlight the characters inside them. I'm not sure how to do that using the simple mode.
There are still three meaningful shortcomings:
- The simple mode we use for defining a language syntax in CodeMirror …
> Update FSH Syntax highlighting

- src/tests/components/FSHControls.test.js
This PR adds a unit test checking that the Examples modal is properly populated from the `examplesConfig` prop passed into the `FSHControls` component. 
I wasn't able to get clicks on the actual example objects in the file tree to be recognized. This limited what I was able to actually test for, as I wasn't able to test that child examples are being rendered properly or that the actual example text is being fetched properly without being able to click objects in the file tree. I've included a second unit test in this PR (commented out) that shows the second test case that I think should be represented. If anyone has a workaround or knows of something that I'm doing wrong here, I'm all ears!
> FSH Examples unit test

- package-lock.json
- src/components/FSHControls.js
Because the dividing space between the two editors got wider, the space between the two convert buttons no longer aligns. It really bugs me and was easy to fix, so I made a PR for it. I'll add screenshots of the differences, but you can also see the difference by looking at https://fshschool.org/FSHOnline/#/ and this branch.
On the deployed FSH Online site now, the space between the buttons does not align with the space between the editors:
On this branch, it does align:
I think they might still be a hair off, but this feels much better to me.
> Realign Convert Buttons

- src/components/JSONOutput.js
- src/tests/components/JSONOutput.test.js
- src/utils/FSHHelpers.js
This PR updates the organization of the JSON files we display on the far right side of the page. Instead of grouping definitions by the FHIR `resourceType`, they are now grouped by the FSH entity type that they came from or will become when running GoFSH. This reflects the default output style of GoFSH once we release a new version. I don't think that the GoFSH release should hold up the merge of this PR since it is still a valid way to organize the files.
The one area I'd definitely like feedback on is if the criteria I'm using for differentiating between Profiles, Extensions, Logical Models, and Resources is sufficient. I used the criteria from GoFSH [here](https://github.com/FHIR/GoFSH/blob/master/src/processor/LakeOfFHIR.ts#L92-L112) (which I believe @mint-thompson added recently). It …
> Update JSON file list to organize by FSH entity

- src/App.js
- src/components/CodeMirrorComponent.js
- src/components/FSHControls.js
- src/components/FSHOutput.js
- src/components/ShareLink.js
- src/tests/components/ShareLink.test.js
This addresses [CIMPL-711](https://standardhealthrecord.atlassian.net/browse/CIMPL-711) by adding support for sharing configuration information when sharing links. If there is information entered into the config modal, and you share a set of FSH, when you visit the generated link, the configuration information should be prepopulated with what was there when you generated the link.
> Support sharing configuration in links

- src/utils/Load.js
This fixes the bug found [here](https://github.com/FSHSchool/FSHOnline/pull/65#issuecomment-889976876).
When using hl7.fhir.us.core#4.0.0 as a dependency, there is a bundle that does not have an id. This causes FSH Online to crash because we use both `id` and `resourceType` to create a keypath to the resource in indexedDB.
@ngfreiter helped me accomplish this great solution.
> Don't add resources without an id or resourceType

- package-lock.json
- package.json
- src/components/TopBar.js
Upgrades the FSHOnline's fsh-sushi dependency to version 2.0.0.
> Update to SUSHI 2.0.0 (stable)

- package-lock.json
- package.json
- src/components/JSONOutput.js
- src/components/TopBar.js
- src/utils/FSHHelpers.js
This updates FSHOnline to use GoFSH 1.3.0. Some of the functions changed slightly and needed to be updated, and the boxes at the end of the output also needed to be edited to match what GoFSH now logs.
> Update to use GoFSH 1.3.0

- src/components/CodeMirrorComponent.js
This PR replaces "tabs" with spaces when you hit the tab key.
I noticed this recently and took a look while starting on the new syntax highlighting because I thought it would be something in the syntax/language mode, but it turns out you can set the setting directly on the editor. Technically, this adds the replacement for both the JSON editor and the FSH editor, but I was testing out the JSON editor, and it looks like when it auto-indents when you hit enter while typing some JSON, it inserts spaces, so I actually think this makes things more consistent there too.
In the FSH editor, if you type something like this:
```
Instance: Bob
InstanceOf: Patient
* name
* given = "Bob"
```
and you hit tab to indent to the `* given  = "Bob"` line, two spaces will be inserted now. On the deployed …
> Replace Tab with Spaces

- src/components/ConsoleComponent.js
This PR make it so the Console automatically opens if it is not already open when a problem occurs. It can still be collapsed and reopened after it initially opens itself. It only opens if a problem occurs - if there are no issues logged, it will stay closed if it is already closed.
> Open Console when it is closed and a problem occurs

- src/components/CodeMirrorComponent.js
This PR fixes [CIMPL-949](https://standardhealthrecord.atlassian.net/browse/CIMPL-949).
The issue that caused the incorrect syntax highlighting in FSH Online was actually not caused by URL matching. Instead, it was caused by too generous of comment matching. The example where I first noticed this actually wasn't matching on a URL, but on a code like `http://foo#bar`. Because it was missing the `.com`/`.org`/etc portion of the URL, it was not matching the URL regex, which is correct. However, the comment regex was too flexible and was matching on the `//` when it should not have been.
The VS Code extension only matches on comments that either start the line or are preceded by whitespace (seen [here](https://github.com/standardhealth/vscode-language-fsh/blob/master/syntaxes/fsh.tmLanguage.js …
> Improve Comment Highlighting

- package-lock.json
- package.json
- src/components/TopBar.js
This updates FSH Online to use the latest release of GoFSH. I tested this with [GoFSH #186](https://github.com/FHIR/GoFSH/issues/186) and confirmed that the latest version of GoFSH works in FSH Online and that the bug that is shown there and fixed in 1.6.1 is properly created in FSH Online.
> Update GoFSH to v1.6.1

- package-lock.json
- package.json
- src/App.js
- src/components/FSHControls.js
- src/tests/components/FSHControls.test.js
- src/tests/utils/FSHHelpers.test.js
- src/tests/utils/Load.test.js
- src/tests/utils/Processing.test.js
- src/tests/utils/helpers.test.js
- src/utils/FSHHelpers.js
- src/utils/Load.js
- src/utils/Processing.js
- src/utils/helpers.js
This PR adds support for FHIR R5 as a configurable FHIR version. In order to support this, a couple functions were added to properly detect what the `'latest'` version of a package is. This allows us to use the automatic dependencies required for R5, `hl7.terminology.r4#latest` and `hl7.fhir.uv.extensions#latest`.
Also, since `'latest'` is now supported, the `hl7.terminology.r4#latest` package is also loaded for any FHIR version, which mirrors SUSHI's behavior.
These packages are included when running both SUSHI and GoFSH. Right now, GoFSH does not add these automatic dependencies, but it will in the future.
I made three other small changes included here:
- Updated the example text to use the current published version of US Core in …
> Support FHIR R5

- src/components/FSHControls.js
- src/tests/components/FSHControls.test.js
Add a short blurb with a link to the repo that holds the examples. Previously, this was only in the README file, but it would be useful to have it in the app itself.
Two small pieces to consider when reviewing this:
- Is the text too prominent? I could make it smaller and/or lighter, but I didn't want to get unnecessarily fancy. Let me know if you'd like screenshots of these options to consider. _**Edit**: I decided to make the font size "small" so now this question is better posed as - is it too small? not prominent enough?_
- How do you feel about the wording? It's a little joke-y, so I could definitely simplify it with something just like "View and add to the examples collection on Github".
> Add a link to the FSH Online Examples repo

- src/utils/FSHHelpers.js
- src/utils/Load.js
- src/utils/Processing.js
- src/utils/logger.js
This makes it so that FSH Online shows the correct number of errors and warnings in the summary box when running GoFSH. GoFSH previously hadn't had the correct number of errors and warnings for two reasons:
When FSH Online was logging any messages (this pretty much only happens in the `run` functions for SUSHI/GoFSH and when loading the FHIR definitions), it was only using the logger from SUSHI. This meant that if you encountered any of the errors logged within FSH Online itself when running GoFSH, it was not included in the "stats" at the bottom of the summary box. In order to fix this issue, I created a util export for a logger that FSH Online can use and a function that sets that logger. This lets the logger get reset when we start to run either GoFSH or SUSHI so that the correct …
> Use separate SUSHI and GoFSH logger and stats

- package.json
Fixes #140 
This PR updates the `browserslist` in `package.json` to just specify the default values. This is what the [browserslists library documents as best practice](https://github.com/browserslist/browserslist#best-practices), so I think it makes sense for us to use this. I think this is changing how the code is built, which is why the error is not seen anymore. Using the default does exclude some old browsers, though, so if you don't think this is a sufficient solution, let me know.
To test this, build the app and serve the production build and test that the two examples convert FSH to FHIR successfully.
> Update to the recommended 'defaults' value for browserslist

- README.md
- package-lock.json
- package.json
- scripts/serve-build.js
The serve-build script serves up the static build. This allows developers to more easily test the built application.
To test it, first run `npm run build` and then run `npm run serve-build`. After that, go to the URL printed to the console and try FSH Online.
Also try deleting the `build` folder and running `npm run serve-build`. You should get a helpful message.
> Add serve-build script

- src/components/JSONOutput.js
- src/tests/components/JSONOutput.test.js
This PR improves handling for examples of Logical Models (or any JSON) that does not have an `id`. If there is no `id`, we try to calculate a related "display" to use in the sidebar on the right and on the top of the editor next to "FHIR JSON:". If there is no `id` or `resourceType`, then we'll fall back to the usual 'Untitled'.
To test this, you can try out using the new example of logical models that was recently contributed on this branch: [here](https://fshschool.org/FSHOnline/#/share/4botLUg).
> Update display for resources without id or resourceType

- src/utils/FSHHelpers.js
This PR updates FSH Online to automatically load dependencies that are more in line with SUSHI's current implementation. We use the `latest` version of `hl7.fhir.uv.tools` (rather than `current`, like SUSHI) because FSH Online does not support `current` versions at the moment. The `hl7.terminology` and `hl7.fhir.uv.extensions` packages are now loaded based on the current FHIR version being used, similar to SUSHI.
I made a small refactor to the code in the second commit because it seemed simpler.
You can test this by changing to the different FHIR versions FSH Online supports and ensuring that the proper packages are loaded for each one.
> Update automatically loaded dependencies

- package-lock.json
- package.json
These scripts set an environment variable before invoking react-app-rewired. The syntax for doing this is different on Windows systems. Two new scripts are defined to make these actions available to Windows users.
> Add variations on start and build scripts for Windows systems

- package-lock.json
- package.json
- src/components/TopBar.js
Updates to the latest SUSHI and GoFSH versions.
I tested out new features from both, and everything worked as expected. I did have to add the same override we needed for SUSHI now that we're using a newer GoFSH.
> Update to SUSHI 3.9.0 and GoFSH 2.3.1

- src/App.js
- src/components/CodeMirrorComponent.js
- src/components/FSHControls.js
- src/components/FSHOutput.js
- src/components/JSONOutput.js
- src/tests/App.test.js
- src/tests/components/CodeMirrorComponent.test.js
- src/tests/components/FSHControls.test.js
This PR includes:
- Functionality to display code with line wrapping in the code editors
- Checkbox for user selection of this functionality
> Text editors support line wrapping

- .github/pull_request_template.md
- BEST-PRACTICES.md
- CONTRIBUTING.md
- package.json
This PR adds the Best Practice document, a PR template, and updates the Contributing document with the latest updates.
This Best Practice document updates the testing framework bullet point to include the React Testing Library and removes the requirement to check coverage since we don't generate a coverage report in this repo. It also updates to use the `lint-fix` command that exists in this repo, and it turns out this repo never had a `prettier-fix` command, so I added one and documented the slight difference in command name. I also removed the requirement to update FSH School documentation since we don't document FSH Online there beyond linking it.
> Best Practices

- package.json
- src/App.jsx
**Description:** This PR fixes a bug that was causing examples with spaces in their path (e.g., `Code Systems`, `Rule Sets`, and `Value Sets` examples) to load as `404: Not Found`. The issue was that the constructed example URLs had a double-slash (`//`) where a single slash (`/`) should be -- which caused GitHub to issue an HTTP 301 redirect, but in doing so, it re-encoded the `%` in `%20`, resulting in an invalid URL.
I've also added a script to enable `npm run check` for consistency with other FSH repos.
**Testing Instructions:** Run FSH Online and confirm that you can load examples in `Code Systems`, `Rule Sets`, and `Value Sets`. Run `npm run check` and confirm it runs the tests, lint, and prettier.
**Related Issue:** N/A
> Fix Example URLs

- .github/workflows/deploy-workflow.yaml
- README.md
- SECURITY.md
- index.html
- public/manifest.json
- src/App.jsx
- src/components/FSHControls.jsx
- src/components/ShareLink.jsx
- tests/App.test.jsx
- tests/AppRouter.test.jsx
- tests/components/FSHControls.test.jsx
- tests/components/ShareLink.test.jsx
- vite.config.mjs
**Description:** The FSHOnline and FSHOnline-Examples repos are moving to the GitHub FHIR organization. Due to how GitHub pages work, this necessitates moving FSH Online from https://fshschool.org/FSHOnline to https://fshonline.fshschool.org. This PR contains the changes necessary to serve the app at that subdomain, as well as changing links from github.com/FSHSchool/* to github.com/FHIR/*.
The PR should only be merged _after_ the repositories have been moved to the github.com/FHIR organization. In addition to merging this PR, the fshschool.org domain will need to be configured as described [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain).
* Note since we are using a …
> Move FSHOnline to https://fshonline.fshschool.org/

- src/components/JSONEditor.jsx
- tests/components/JSONEditor.test.jsx
**Description:**
This PR avoids returning an object as the `id` value that is used when we display FHIR artifacts in the JSON editor sidebar.
When an `id` is set using an instance, the `id` property is an object, not a string. However, FSH Online assumed `id` was always a string value and passed it to components assuming it was a string.
To handle this, I updated the `checkIdToDisplay` function that we use to determine an `id` value to better handle objects.
**Testing Instructions:**
The main goal of this PR was just to prevent FSH Online from crashing. You can test this by using the following FSH:
```
Instance: MyId
InstanceOf: string
Usage: #inline
* value = "my-id"
Instance: MyObs
InstanceOf: Observation
* id = MyId
* code = #123
* status = #final
```
On master (and the deployed FSH …
> Avoid using an object when displaying id in JSON editor sidebar

- src/App.jsx
- src/components/FSHControls.jsx
- src/utils/FSHHelpers.js
- src/utils/logger.js
- tests/components/FSHControls.test.jsx
**Description:** This PR adds a debug log level option to the configuration settings menu to allow a user to toggle the debug level messages that appear in the console.
**Testing Instructions:** Run jest unit tests and view within browser.
**Related Issue:** n/a
> console debug log level

- src/App.jsx
- src/components/TopBar.jsx
**Description:**
I wanted to send a little gift to FSH online users before my work on FSH projects officially ends. Now you can say ahoy to the little fish that lives in the corner of the top bar.
**Testing Instructions:**
When running FSH Online, try setting your canonical URL to `ahoy to fsh`. The fish in the top bar will say ahoy, and you should see a nice little message in the console.
**Related Issue:**
N/A
> add a little gift from the FSH mascot

- src/components/Console.jsx
- src/theme.js
- vite.config.mjs
**Description:**
This is a small PR to add a block of color over the log level for messages in the Console.
Note that the "results" box isn't colored like it is for SUSHI and GoFSH in the terminal.
**Testing Instructions:**
Try out FSH Online and view different messages at different log levels. Make sure to view an info, error, warning, and debug level message.
**Related Issue:** 
Fixes #180 (with the exception of coloring the results box).
> Color level of log message
